### ISSUE TITLE
博客系统安装完成后管理员权限发表文章后，在主页查看文章出现错误

### ISSUE THREAD

**Issue by alobe** [BadTudou/blog#1]
具体错误类型是404，后台存储倒是生成了相对应的html文件，请问要怎么解决呢？

**Comment by BadTudou-zz** [comment]
文件的存储路径，我记得是在默认“/public/html/article”，你可以看conf/conf.js文件。在管理中更改后，由于是更改js中的内容，好像不会立即生效，你重启项目试一下。最好的解决办法是，开启浏览器的调试模式，一般是F12，看看你访问的链接（会报404错误的那个），然后看看配置文件中的文章保存路径，对比一下。开启调试模式会有很多信息，我记得也包括配置信息。如果还是不行，加QQ1217473249。以前写的，很久没更新，也没维护优化整理什么，代码烂，见谅

**Comment by BadTudou-zz** [comment]
最好的方法是手动更改conf/conf.js中配置信息，重启项目
